name: NodeJS with Gulp

on:
  push:
    branches: [ "master", "ci" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.15.0]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.2'
        bundler-cache: true
    - run: gulp build
    - uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site # The folder the action should deploy.
